<?php
/**
 * Created by PhpStorm.
 * User: execut
 * Date: 11/29/16
 * Time: 3:26 PM
 */

namespace execut\scheduler\actions\adapter;


use execut\actions\action\adapter\Simple;
use execut\actions\action\adapter\viewRenderer\Widget;
use yii\helpers\ArrayHelper;

class Schedule extends Simple
{
    public $urlAttribute = null;
    public $model = null;
    public function getDefaultViewRendererConfig()
    {
        $jobs = [];
        foreach (\execut\import\models\ImportSettings::find()->addOrderBy('name ASC')->all() as $importSetting) {
            $jobs[] = [
                'key' => $importSetting->id,
                'label' => $importSetting->name,
            ];
        }

        $config = parent::getDefaultViewRendererConfig(); // TODO: Change the autogenerated stub
        $urlParams = [];
        if ($this->model) {
            $attribute = $this->urlAttribute;
            $urlParams[$attribute] = $this->model->id;
        }

        $urlParams = ArrayHelper::merge(['/scheduler/default/data'], $urlParams);
        $config = array_merge($config, [
            'class' => Widget::className(),
            'widget' => [
                'class' => \execut\scheduler\widget\Schedule::className(),
                'clientOptions' => [
                    'positionDate' => time() * 1000,
                    'url' => \yii\helpers\Url::to($urlParams),
                    'otherSections' => [
                        [
                            'name' => 'importSettingId',
                            'options' => $jobs,
                            'map_to' => 'importSettingId',
                            'type' => 'multiselect',
                            'vertical' => true,
                            'height' => 200,
                            'default_value' => $this->model ? (string) $this->model->id : null,
                        ],
                    ],
                ],
            ],
        ]);

        return $config;
    }

    public function getView() {
        if (is_array($this->view)) {
            $this->view = \yii\helpers\ArrayHelper::merge($this->view, $this->getDefaultViewRendererConfig());
        }

        $view = parent::getView();
        return $view;
    }
}