<?php
/**
 * Created by PhpStorm.
 * User: execut
 * Date: 8/1/17
 * Time: 3:04 PM
 */

namespace execut\scheduler;


class Bootstrap extends \execut\yii\Bootstrap
{
    public $_defaultDepends = [
        'modules' => [
            'scheduler' => Module::class,
        ],
    ];

    public function bootstrap($app)
    {
        parent::bootstrap($app); // TODO: Change the autogenerated stub
        if (empty($app->aliases['@execut'])) {
            $app->setAliases(['@execut' => '@vendor/execut']);
            $app->setAliases(['@execut/scheduler' => '@execut/yii2-scheduler']);
        }
    }
}